export const FILTER_PLAYER = 'FILTER_PLAYER';
export const ADD_PLAYER = 'ADD_PLAYER';
export const STAR_PLAYER = 'STAR_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const SET_CURRENT_PLAYERS = 'SET_CURRENT_PLAYERS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

