export const ADD_PLAYER = 'ADD_PLAYER';
export const STAR_PLAYER = 'STAR_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const PAGE_CURRENT_CHANGE_PLAYER = 'PAGE_CURRENT_CHANGE_PLAYER';
