export const ADD_PLAYER = 'ADD_PLAYER';
export const STAR_PLAYER = 'STAR_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const TAB_STATUS_SWITCH = 'TAB_STATUS_SWITCH';
export const PAGE_CHANGE_INDEX =  'PAGE_CHANGE_INDEX'
